const ADD_TODO_ITEM = 'ADD_TODO_ITEM';
const FETCH_TODO_ITEMS = 'FETCH_TODO_ITEMS';
const FETCH_LIST_ITEM = 'FETCH_LIST_ITEM';
const LIST_ITEM_RECEIVED = 'LIST_ITEM_RECEIVED';

module.exports = {
  ADD_TODO_ITEM,
  FETCH_TODO_ITEMS,
  FETCH_LIST_ITEM,
  LIST_ITEM_RECEIVED,
}