const ADD_TODO_ITEM = 'ADD_TODO_ITEM';
const FETCH_LIST_ITEM = 'FETCH_LIST_ITEM';
const LIST_ITEM_RECEIVED = 'LIST_ITEM_RECEIVED';
const SET_SEARCH_TERM = 'SET_SEARCH_TERM'; 

module.exports = {
  ADD_TODO_ITEM,
  FETCH_LIST_ITEM,
  LIST_ITEM_RECEIVED,
  SET_SEARCH_TERM,
}